### Numpy

In [1]:
import numpy as np

#### Difference between np.Array and List

vector addition and concatenation

In [8]:
a = np.array([1,2,3])
l = [1,2,3]


#vector addition 
b = a + a
l2 = l + l #this does list concatination
print("vector addition: a + a = {0}".format(b))
print("concatenation of lists: l + l = {0}".format(l2))
print("adding an element to lists: l + [4] = {0}".format(l+[4]))

vector addition: a + a = [2 4 6]
concatenation of lists: l + l = [1, 2, 3, 1, 2, 3]
adding an element to lists: l + [4] = [1, 2, 3, 4]


accessing elements of matrix

In [70]:
m = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print(m[0,1])  #matlab way
print(m[0][1]) #array way

2
2


Scalar multiplication

In [31]:

print("elementwise multiplication: {0} * {0} = {1}".format(a, a*a))
print("scalar multiplication: {1} * 2 = {0}".format(a*2,a))
print("multiplying list with a number (repeats the element 'number' of times): {1} * 2 = {0}".format(l2,l))
#print("adding an element to lists: l + [4] = {0}".format(l+[4]))

elementwise multiplication: [1 2] * [1 2] = [1 4]
scalar multiplication: [1 2] * 2 = [2 4]
multiplying list with a number (repeats the element 'number' of times): [1, 2, 3] * 2 = [1, 2, 3, 1, 2, 3]


In [12]:
print("elementwise sqrt: np.sqrt({1}) = {0}".format(np.sqrt(a),a))
print("elementwise log: np.log({1}) = {0}".format(np.log(a),a))
print("elementwise exp: np.exp({1}) = {0}".format(np.exp(a),a))

elementwise sqrt: np.sqrt([1 2 3]) = [ 1.          1.41421356  1.73205081]
elementwise log: np.log([1 2 3]) = [ 0.          0.69314718  1.09861229]
elementwise exp: np.exp([1 2 3]) = [  2.71828183   7.3890561   20.08553692]


Dot product

In [17]:
a = np.array([1,2])
b = np.array([2,1])

ab = np.sum(a*b)
print("Dot product of {0}.{1} = {2}".format(a,b,ab))
print("Dot product of np.dot({0},{1}) = {2}".format(a,b,np.dot(a,b)))

Dot product of [1 2].[2 1] = 4
Dot product of np.dot([1 2],[2 1]) = 4


Angle between vectors

In [19]:
cosangle = np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))
angle = np.arccos(cosangle)
print("Angle between vectors np.dot(a,b)/(np.linalg.norm(a) * np.linalg.norm(b)) = {0}".format(cosangle))
print("Angle between vectors {0} and {1} = {2}".format(a,b, angle))

Angle between vectors np.dot(a,b)/(np.linalg.norm(a) * np.linalg.norm(b)) = 0.7999999999999998
Angle between vectors [1 2] and [2 1] = 0.6435011087932847


Matrix LinAlg

In [28]:
A = np.array([[1,2],[3,4]])
Ainv = np.linalg.inv(A)
Adet = np.linalg.det(A)
print("Inverse of \n {0} : \n {1}".format(A, Ainv))
print("Determinant of \n {0} : {1}".format(A, Adet))

Inverse of 
 [[1 2]
 [3 4]] : 
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of 
 [[1 2]
 [3 4]] : -2.0000000000000004


### Solving Linear equations
A x = B

In [37]:
A = np.array([[1,2],[3,4]])
b = np.array([1,2])
x = np.linalg.inv(A).dot(b)
print ("x = {0}".format(x))

x = [  2.22044605e-16   5.00000000e-01]


#### using np.linalg.solve()

In [40]:
np.linalg.solve(A, b)

array([ 0. ,  0.5])

### Loading data file using numpy

In [49]:
X = [] # declare list to hold the data

for line in open('data_2d.csv'):
    row_s = line.split(',')
    row = list(map(float, row_s)) #change string to float
    X.append(row)

#convert to list of list to matrix in np
X = np.array(X)
X.shape

(100, 3)

In [50]:
X[:3]

array([[  17.93020121,   94.52059195,  320.2595296 ],
       [  97.14469719,   69.59328198,  404.63447153],
       [  81.77590078,    5.7376481 ,  181.48510774]])

## Pandas

In [53]:
import pandas as pd

X = pd.read_csv("data_2d.csv", header = None)
X.shape

(100, 3)

In [54]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
0    100 non-null float64
1    100 non-null float64
2    100 non-null float64
dtypes: float64(3)
memory usage: 2.4 KB


In [55]:
X.head()

0          1           2
0  17.930201  94.520592  320.259530
1  97.144697  69.593282  404.634472
2  81.775901   5.737648  181.485108
3  55.854342  70.325902  321.773638
4  49.366550  75.114040  322.465486

dataframe to numpy array

In [59]:
M = X.as_matrix()
M[:3]

array([[  17.93020121,   94.52059195,  320.2595296 ],
       [  97.14469719,   69.59328198,  404.63447153],
       [  81.77590078,    5.7376481 ,  181.48510774]])

In [61]:
X[0] #returns column with name as 0

0     17.930201
1     97.144697
2     81.775901
3     55.854342
4     49.366550
5      3.192702
6     49.200784
7     21.882804
8     79.509863
9     88.153887
10    60.743854
11    67.415582
12    48.318116
13    28.829972
14    43.853743
15    25.313694
16    10.807727
17    98.365746
18    29.146910
19    65.100302
20    24.644113
21    37.559805
22    88.164506
23    13.834621
24    64.410844
25    68.925992
26    39.488442
27    52.463178
28    48.484787
29     8.062088
        ...    
70    30.187692
71    11.788418
72    18.292424
73    96.712668
74    31.012739
75    11.397261
76    17.392556
77    72.182694
78    73.980021
79    94.493058
80    84.562821
81    51.742474
82    53.748590
83    85.050835
84    46.777250
85    49.758434
86    24.119257
87    27.201576
88     7.009596
89    97.646950
90     1.382983
91    22.323530
92    45.045406
93    40.163991
94    53.182740
95    46.456779
96    77.130301
97    68.600608
98    41.693887
99     4.142669
Name: 0, Length: 100, dt

In [62]:
type(X[0])

pandas.core.series.Series

Accessing elements via index

Accessing 1st row and 0th element

In [64]:
X.iloc[1,0]

97.144697185200002

Access 1st row

In [65]:
X.iloc[1] 

0     97.144697
1     69.593282
2    404.634472
Name: 1, dtype: float64

#### Selecting two columns

In [67]:
X[[0,2]].head()

0           2
0  17.930201  320.259530
1  97.144697  404.634472
2  81.775901  181.485108
3  55.854342  321.773638
4  49.366550  322.465486

#### Filtering rows

In [68]:
#all rows with 0th element less than 5
X[ X[0] < 5]

0          1           2
5   3.192702  29.256299   94.618811
44  3.593966  96.252217  293.237183
54  4.593463  46.335932  145.818745
90  1.382983  84.944087  252.905653
99  4.142669  52.254726  168.034401